Add EL9 support
voxpupuli/puppet-augeasproviders_sysctl pull request #84
Opened 2023-10-30 13:27 UTC by bastelfreak

Also contains #83

2023-11-06 13:47 UTC, ekohl requested changes
Test failures look relevant.

2024-12-05 15:28 UTC, ghoneycutt commented
CentOS 9 and OracleLinux 9 should not be in the list at all. Instead we should have Rocky 9.

2024-12-05 17:25 UTC, ekohl commented
> CentOS 9 and OracleLinux 9 should not be in the list at all. Instead we should have Rocky 9.

Why? In pretty much all other repositories we at least include CentOS 9.

2024-12-08 15:20 UTC, treydock commented
@bastelfreak The issue is this:

```
/augeas/files/etc/sysctl.d/20-fs.conf/error/message = No such file or directory
Error: /Stage[main]/Main/Sysctl[fs.nr_open]: Could not evaluate: Failed to save Augeas tree to file. See debug logs for details.
Debug: Executing: '/usr/sbin/sysctl -n fs.inotify.max_user_watches'
```

By default RHEL9 doesn't have `/etc/sysct.d`.  That's provided by `systemd-udev` package.  What is the mechanism with VP beaker to inject a new package for tests?

2026-04-29 19:49 UTC, silug commented
Change implemented in #99

2026-04-29 19:49 UTC, closed without merging